# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e94610b63cee6804002d3e0e296ecdf75aa6de56b1d09f6a7c08ed0069a8622429857c46ddfb822953cb03856226cba0635542da23dd2fb9d4ccb5def0f34eb

test:
  secret_key_base: e302cdf0235f262156c07cb5730b0a9eaeb96f1bcf325096be89a11d1fcaeedf5dc172b061bc6b321f3d2e97911c2c5ca5f43774c68637243fc0d4bbf928964d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
